[package]
name = "eth-bridge-rpc"
description = 'Polkaswap RPC for farming operations.'
edition = "2021"
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'
version = "0.1.0"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2" }
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9" }
sp-api = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9" }
sp-blockchain = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9" }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9" }
sp-rpc = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9" }
eth-bridge = { path = "../" }
eth-bridge-runtime-api = { path = "../runtime-api" }
common = { path = "../../../common" }
