[package]
name = "eth-bridge-rpc"
authors = []
description = 'Polkaswap RPC for farming operations.'
edition = "2018"
license = 'MIT OR Apache-2.0'
repository = 'https://github.com/soramitsu/sora2-substrate/'
version = "0.1.0"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2" }
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"
sp-runtime = "3"
sp-api = "3"
sp-blockchain = "3"
sp-std = "3"
sp-core = "3"
sp-rpc = "3"
eth-bridge = { path = "../" }
eth-bridge-runtime-api = { path = "../runtime-api" }
common = { path = "../../../common" }
