[package]
name = "framenode-chain-spec"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2", features = ["derive", "chain-error"] }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9" }
hex-literal = "0.3.1"
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9" }
sc-network = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9" }
sc-service = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9" }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9" }

bridge-multisig = { git = "https://github.com/soramitsu/sora2-frame-pallets.git", branch = "v4.0.0-dev", package = "pallet-multisig" }

common = { path = "../../common" }
faucet = { path = "../../pallets/faucet", optional = true }
framenode-runtime = { path = "../../runtime" }
iroha-migration = { path = "../../pallets/iroha-migration" }
permissions = { path = "../../pallets/permissions" }
rewards = { path = "../../pallets/rewards" }
technical = {path = "../../pallets/technical" }
xor-fee = { path = "../../pallets/xor-fee" }

[features]
include-real-files = []
main-net-coded = []
test = []

private-net = [
    "faucet",
    "framenode-runtime/private-net",
]
