[package]
name = "framenode-chain-spec"
version = "1.2.2"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3", features = [
    "derive",
    "chain-error",
] }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }
hex-literal = "0.3.1"
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }
sc-network = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }
sc-service = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }

serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.61"

bridge-multisig = { git = "https://github.com/soramitsu/sora2-frame-pallets.git", branch = "polkadot-v0.9.19", package = "pallet-multisig" }

common = { path = "../../common" }
faucet = { path = "../../pallets/faucet", optional = true }
framenode-runtime = { path = "../../runtime" }
iroha-migration = { path = "../../pallets/iroha-migration" }
permissions = { path = "../../pallets/permissions" }
rewards = { path = "../../pallets/rewards" }
technical = { path = "../../pallets/technical" }
xor-fee = { path = "../../pallets/xor-fee" }

[features]
include-real-files = []
main-net-coded = []
test = []

private-net = ["faucet", "framenode-runtime/private-net"]
