[package]
name = "iroha-migration-rpc"
version = "0.1.0"
edition = "2018"

[dependencies]
jsonrpc-core = { version = "15.0.0", default-features = false }
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"
sp-runtime = { version = "3" }
sp-api = { version = "3" }
sp-blockchain = { version = "3" }
sp-rpc = { version = "3" }

# Path dependencies
common = { path = "../../../common" }
iroha-migration-runtime-api = { path = "../runtime-api" }
