[workspace]
members = [
    "runtime/",
    "common",
    "pallets/assets",
    "pallets/parachain-info",
    "pallets/permissions",
    "pallets/token-dealer",
    "pallets/trading-pair",
    "pallets/dex-manager",
    "pallets/template",
    "pallets/technical",
    "pallets/xor-fee",
    "pallets/referral-system",
    "pallets/bonding-curve-pool",
    "node/",
]

[profile.release]
panic = 'unwind'
