[workspace]
members = [
        "runtime/",
        "common",
        "pallets/parachain-info",
        "pallets/permissions",
        "pallets/token-dealer",
        "pallets/trading-pair",
        "pallets/dex-manager",
        "pallets/template",
        "node/",
]

[profile.release]
panic = 'unwind'
