[package]
name = "farming-runtime-api"
version = "0.1.0"
edition = "2018"
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'

[dependencies]
sp-std = { version = "3", default-features = false }
sp-api = { version = "3", default-features = false }
codec = { package = "parity-scale-codec", version = "2", default-features = false }

[features]
default = ["std"]
std = [
    "sp-api/std",
    "sp-std/std",
    "codec/std",
]
