[package]
name = "substrate-gen"
version = "0.1.0"
edition = "2021"

[build-dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
    "chain-error",
] }
scale-info = { version = "2", default-features = false, features = [
    "derive",
] }
framenode-runtime = { path = "../../runtime", default-features = false, features = ["std", "private-net"] }
hex = "0.4.3"

[dependencies]
common = { path = "../../common" }
subxt = { git = "https://github.com/paritytech/subxt", rev = "e0439c91abdec73809fc36e337ec2dc808734e36" }
codec = { package = "parity-scale-codec", version = "3", features = ["derive"] }
scale-info = { version = "2", features = ["derive"] }
bridge-types = { path = "../../pallets/trustless-eth-bridge/types" }
beefy-primitives = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }
