[package]
name = "eth-bridge"
version = "0.1.0"
authors = ["Vladislav Markushin <markushin@soramitsu.co.jp>"]
edition = "2018"

[dependencies]
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
sp-core = { version = "2.0.0", default-features = false }
ethereum-types = { version = "=0.9.4", default-features = false, features = ['serialize_no_std', 'codec'], git = "https://github.com/vmarkushin/parity-common.git", branch = "no-std", package = "ethereum-types" }
ethabi = { version = "12.0.3", default-features = false, git = "https://github.com/vmarkushin/ethabi.git", branch = "no-std", package = "ethabi" }
jsonrpc-core = { version = "16.0.1", default-features = false, git = "https://github.com/vmarkushin/jsonrpc.git", branch = "no-std", package = "jsonrpc-core" }
rlp = { version = "0.4.6", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }
alt_serde = { version = "1", default-features = false, git = "https://github.com/vmarkushin/serde.git", features = ["alloc", "derive"], package = "serde" }
serde_json = { version = "1", default-features = false, git = "https://github.com/vmarkushin/json.git", features = ["alloc"], package = "serde_json" }
common = { path = "../../common", default-features = false }
assets = { path = "../assets", default-features = false }
serde = { version = "1.0.101", optional = true, features = ["derive"], default-features = false }
multisig = { git = "https://github.com/soramitsu/sora2-frame-pallets.git", branch = "vmarkushin/multisig", package = "pallet-multisig", default-features = false }
libsecp256k1 = { version = "0.3.5", features = ['hmac'], default-features = false }
tiny-keccak = { version = "2", default-features = false }
hex-literal = "0.3.1"

[dev-dependencies]
parking_lot = "0.10.0"
async-std = { version = "1.5", features = ["attributes", "unstable"] }
parity-util-mem = { version = "0.7.0", default-features = false }
pallet-balances = { version = "2.0.0" }
pallet-sudo = { version = "2.0.0" }
frame-executive = { version = "2.0.0", default-features = false }
common = { path = "../../common", default-features = false, features = ["test"] }
permissions = { path = "../permissions", default-features = false }
tokio = { version = "0.2.13", default-features = false, features = ["macros"] }
env_logger = "0.8.1"
currencies = { version = "0.3.2", package = "orml-currencies", default-features = false }
tokens = { version = "0.3.2", package = "orml-tokens", default-features = false }
orml-traits = { version = "0.3.2", package = "orml-traits", default-features = false }
sp-core = { version = "2.0.0", default-features = false, features = ["full_crypto"] }

[dependencies.codec]
default-features = false
features = ['derive', 'full']
package = 'parity-scale-codec'
version = '1.3.1'

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'multisig/std',
    'assets/std',
    'sp-std/std',
    'sp-core/std',
    'ethereum-types/std',
    'ethabi/std',
    'rlp/std',
    'alt_serde/std',
    'serde_json/std',
    'jsonrpc-core/std',
    'rustc-hex/std',
    'common/std',
    'libsecp256k1/std',
]