[package]
name = 'parachain-runtime'
version = '0.1.0'
authors = ["Parity Technologies <admin@parity.io>"]
edition = '2018'

[dependencies]
serde = { version = "1.0.101", default-features = false, optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
hex-literal = "0.3.1"

faucet = { path = "../pallets/faucet", default-features = false }
trading-pair = { path = "../pallets/trading-pair", default-features = false}
trading-pair-runtime-api = { path = "../pallets/trading-pair/runtime-api", default-features = false }
bonding-curve-pool = { path = "../pallets/bonding-curve-pool", default-features = false }
technical = { path = "../pallets/technical", default-features = false}
pool-xyk = { path = "../pallets/pool-xyk", default-features = false}
parachain-info = { path = "../pallets/parachain-info", default-features = false}
permissions = { path = "../pallets/permissions", default-features = false}
cumulus-token-dealer = { path = "../pallets/token-dealer", default-features = false}
dex-manager = { path = "../pallets/dex-manager", default-features = false }
dex-manager-runtime-api = { path = "../pallets/dex-manager/runtime-api", default-features = false }
dex-api = { path = "../pallets/dex-api", default-features = false }
dex-runtime-api = { path = "../pallets/dex-api/runtime-api", default-features = false }
referral-system = { path = "../pallets/referral-system", default-features = false }
xor-fee = { path = "../pallets/xor-fee", default-features = false }
mock-liquidity-source = { path = "../pallets/mock-liquidity-source", default-features = false }
liquidity-proxy = { path = "../pallets/liquidity-proxy", default-features = false }
liquidity-proxy-runtime-api = { path = "../pallets/liquidity-proxy/runtime-api", default-features = false }
template = { package = "pallet-template", path = "../pallets/template", version = "2.0.0-rc5", default-features = false}
template-runtime-api = { path = "../pallets/template/runtime-api", default-features = false }

currencies = { package = "orml-currencies", branch = "rococo-branch", git = "https://github.com/vmarkushin/open-runtime-module-library", default-features = false }
tokens = { package = "orml-tokens", branch = "rococo-branch", git = "https://github.com/vmarkushin/open-runtime-module-library", default-features = false }

# Substrate dependencies
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-offchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-inherents = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }

frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
frame-executive = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
pallet-sudo = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
pallet-transaction-payment = { git = "https://github.com/eadventurous/pallet-transaction-payment", default-features = false, branch = "rococo-branch"}

# Cumulus dependencies
cumulus-runtime = { git = "https://github.com/paritytech/cumulus",  default-features = false, rev = '96da14c14fb785e106bb89a18c9dedaf2f789d2c' }
cumulus-parachain-upgrade = { git = "https://github.com/paritytech/cumulus",  default-features = false, rev = '96da14c14fb785e106bb89a18c9dedaf2f789d2c' }
cumulus-message-broker = { git = "https://github.com/paritytech/cumulus",  default-features = false, rev = '96da14c14fb785e106bb89a18c9dedaf2f789d2c' }
cumulus-upward-message = { git = "https://github.com/paritytech/cumulus",  default-features = false, rev = '96da14c14fb785e106bb89a18c9dedaf2f789d2c' }
cumulus-primitives = { git = "https://github.com/paritytech/cumulus",  default-features = false, rev = '96da14c14fb785e106bb89a18c9dedaf2f789d2c' }

# Additional dependencies
common = { path = "../common", default-features = false }
assets = { path = "../pallets/assets", default-features = false }
assets-runtime-api = { path = "../pallets/assets/runtime-api", default-features = false }
#iroha-bridge = { path = "../pallets/iroha-bridge", default-features = false }
static_assertions = "1.1.0"

[build-dependencies]
substrate-wasm-builder-runner = { version = "1.0.6" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"serde",
	"sp-api/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-version/std",
	"sp-offchain/std",
	"sp-session/std",
	"sp-block-builder/std",
	"sp-transaction-pool/std",
	"sp-inherents/std",
	"frame-support/std",
	"frame-executive/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-randomness-collective-flip/std",
	"pallet-timestamp/std",
	"pallet-sudo/std",
	"pallet-transaction-payment/std",
	"parachain-info/std",
	"cumulus-runtime/std",
	"cumulus-parachain-upgrade/std",
	"cumulus-message-broker/std",
	"cumulus-upward-message/std",
	"cumulus-primitives/std",
	"cumulus-token-dealer/std",
	"faucet/std",
	"trading-pair/std",
	"trading-pair-runtime-api/std",
	"bonding-curve-pool/std",
	"technical/std",
	"pool-xyk/std",
	"common/std",
	"template/std",
	"template-runtime-api/std",
	"dex-manager/std",
	"dex-manager-runtime-api/std",
	"dex-api/std",
	"dex-runtime-api/std",
	"liquidity-proxy/std",
	"liquidity-proxy-runtime-api/std",
	"mock-liquidity-source/std",
	"currencies/std",
	"tokens/std",
	"assets/std",
	"assets-runtime-api/std",
	"permissions/std",
]

# Will be enabled by the `wasm-builder` when building the runtime for WASM.
runtime-wasm = [
	"cumulus-upward-message/runtime-wasm",
]
