[package]
name = "farming-rpc"
version = "0.1.0"
edition = "2018"
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'

[dependencies]
codec = { package = "parity-scale-codec", version = "2", default-features = false }
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"
sp-api = { version = "3", default-features = false }
sp-blockchain = { version = "3", default-features = false }
sp-runtime = { version = "3", default-features = false }
farming-runtime-api = { path = "../runtime-api" }
common = { path = "../../../common" }

[features]
default = ["std"]
std = [
  "sp-api/std",
  "sp-runtime/std",
  "farming-runtime-api/std"
]
