[package]
authors = ['Nikita Puzankov <puzankov@soramitsu.co.jp>']
description = 'Polkaswap RPC for farming operations.'
edition = "2018"
license = 'MIT OR Apache-2.0'
name = "farming-rpc"
repository = 'https://github.com/soramitsu/sora2-substrate/'
version = "0.1.0"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2" }
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"
sp-runtime = { version = "3" }
sp-api = { version = "3" }
sp-blockchain = { version = "3" }
sp-std = { version = "3" }
sp-core = { version = "3" }
sp-rpc = { version = "3" }
farming = { path = "../" }
farming-runtime-api = { path = "../runtime-api" }
common = { path = "../../../common" }
