[package]
edition = "2018"
name = "xor-fee-benchmarking"
authors = ["Polka Biome Ltd. <jihoon@tutanota.de>"]
license = "BSD-4-Clause"
homepage = "https://sora.org"
repository = "https://github.com/sora-xor/sora2-network"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = [
    "derive",
] }
frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }

pallet-staking = { git = "https://github.com/soramitsu/sora2-frame-pallets.git", branch = "polkadot-v0.9.12", default-features = false }

assets = { path = "../../assets", default-features = false }
common = { path = "../../../common", default-features = false }
permissions = { path = "../../permissions", default-features = false }
pool-xyk = { path = "../../pool-xyk", default-features = false }
xor-fee = { path = "..", default-features = false }

[features]
default = ["std"]

std = [
    "assets/std",
    "codec/std",
    "common/std",
    "frame-benchmarking/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-staking/std",
    "permissions/std",
    "pool-xyk/std",
    "sp-core/std",
    "sp-std/std",
]
