[package]
authors = ['Alexey Kalita <kalita@soramitsu.co.jp>']
description = 'Pallet for claiming rewards'
edition = '2018'
license = 'MIT OR Apache-2.0'
name = 'rewards'
repository = 'https://github.com/soramitsu/sora2-substrate/'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"] }
frame-support = { version = "3", default-features = false }
frame-system = { version = "3", default-features = false }
libsecp256k1 = { version = "0.3.5", features = ["hmac"], default-features = false }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-core = { version = "3", default-features = false }
sp-io = { version = "3", default-features = false }
sp-std = { version = "3", default-features = false }

assets = { path = "../assets", default-features = false }
common = { path = "../../common", default-features = false }
technical = { path = "../technical", default-features = false }

[dev-dependencies]
currencies = { version = "0.4", package = "orml-currencies" }
hex-literal = "0.3.1"
pallet-balances = { version = "3" }
sp-runtime = { version = "3" }
tokens = { version = "0.4", package = "orml-tokens" }

assets = { path = "../assets" }
common = { path = "../../common", features = ["test"] }
permissions = { path = "../permissions" }
technical = { path = "../technical" }

[features]
default = ['std']

std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'serde',
    'sp-core/std',
    'sp-io/std',
    'sp-std/std',
]
