[package]
name = "iroha-migration-runtime-api"
version = "0.1.0"
edition = "2018"

[dependencies]
sp-api = { version = "3", default-features = false }

[features]
default = ["std"]
std = ["sp-api/std"]
