[package]
name = "ethereum-gen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "abigen"
path = "src/abigen.rs"

[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "4c677933" }
ethers-contract = { git = "https://github.com/gakonst/ethers-rs", rev = "4c677933" }
ethers-core = { git = "https://github.com/gakonst/ethers-rs", rev = "4c677933" }
ethers-providers = { git = "https://github.com/gakonst/ethers-rs", rev = "4c677933" }
serde_json = "1.0.72"
serde = "1.0.131"
anyhow = "1.0.51"
