[package]
name = "ethereum-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "1271308e06bd4c1b6db271488838e011505fcdfa" }
serde_json = "1.0.72"
serde = "1.0.131"
anyhow = "1.0.51"
