[package]
name = "get-lp-tokens"
version = "0.1.0"
authors = ["Alexey Kalita <kalita.alexey@outlook.com>"]
edition = "2021"

[workspace]

[dependencies]
#fixnum = { version = "0.6.0", features = ["i128"] }
fixnum = { git = "https://github.com/vovac12/fixnum", default-features=false, branch = "master", features = ["i128"] }
reqwest = { version = "0.11.2", features = ["blocking", "json"] }
serde = { version = "1.0.125", features = ["derive"] }